// genres.js — GENRE_CONFIG SSOT; pure data + pure helpers; no DOM, no imports, no side effects
// GENERATED by scripts/build_genre_config.py — do not edit manually
// Data: data/everynoise_genre_attrs.csv (Everynoise, frozen 2025)
// Rebuild: python scripts/build_genre_config.py

export const GENRE_CONFIG = {

  mainGenres: [
    { id: 'EDM / Electronic', role: 'peak',
      neighbours: [
        { mainId: 'Deutsche Musik',                     weight: 1.0 },
        { mainId: 'Pop & New Wave',                     weight: 0.7 },
        { mainId: 'Hip Hop / Rap',                      weight: 0.5 },
        { mainId: 'Synthwave / Electronica',            weight: 0.5 },
        { mainId: 'Ska & Reggae',                       weight: 0.5 },
      ]},
    { id: 'Rock', role: 'peak',
      neighbours: [
        { mainId: 'Ska & Reggae',                       weight: 1.0 },
        { mainId: 'Punk',                               weight: 0.7 },
        { mainId: 'Funk, Soul & R&B',                   weight: 0.5 },
        { mainId: 'Metal & Hard Rock',                  weight: 0.5 },
        { mainId: 'Pop & New Wave',                     weight: 0.5 },
      ]},
    { id: 'Pop & New Wave', role: 'peak',
      neighbours: [
        { mainId: 'Deutsche Musik',                     weight: 1.0 },
        { mainId: 'Ska & Reggae',                       weight: 0.7 },
        { mainId: 'Funk, Soul & R&B',                   weight: 0.5 },
      ]},
    { id: 'Metal & Hard Rock', role: 'peak',
      neighbours: [
        { mainId: 'Punk',                               weight: 1.0 },
        { mainId: 'Rock',                               weight: 0.7 },
        { mainId: 'Ska & Reggae',                       weight: 0.5 },
      ]},
    { id: 'Ska & Reggae', role: 'peak',
      neighbours: [
        { mainId: 'Pop & New Wave',                     weight: 1.0 },
        { mainId: 'Deutsche Musik',                     weight: 0.7 },
        { mainId: 'Funk, Soul & R&B',                   weight: 0.5 },
        { mainId: 'Rock',                               weight: 0.5 },
        { mainId: 'Hip Hop / Rap',                      weight: 0.5 },
      ]},
    { id: 'Synthwave / Electronica', role: 'warmup',
      neighbours: [
        { mainId: 'EDM / Electronic',                   weight: 1.0 },
        { mainId: 'Pop & New Wave',                     weight: 0.7 },
        { mainId: 'Deutsche Musik',                     weight: 0.5 },
        { mainId: 'Punk',                               weight: 0.5 },
        { mainId: 'Ska & Reggae',                       weight: 0.5 },
      ]},
    { id: 'Hip Hop / Rap', role: 'peak',
      neighbours: [
        { mainId: 'Deutsche Musik',                     weight: 1.0 },
        { mainId: 'Pop & New Wave',                     weight: 0.7 },
        { mainId: 'Ska & Reggae',                       weight: 0.5 },
        { mainId: 'Funk, Soul & R&B',                   weight: 0.5 },
        { mainId: 'EDM / Electronic',                   weight: 0.5 },
      ]},
    { id: 'Punk', role: 'peak',
      neighbours: [
        { mainId: 'Metal & Hard Rock',                  weight: 1.0 },
        { mainId: 'Rock',                               weight: 0.7 },
        { mainId: 'Ska & Reggae',                       weight: 0.5 },
      ]},
    { id: 'Funk, Soul & R&B', role: 'cooldown',
      neighbours: [
        { mainId: 'Ska & Reggae',                       weight: 1.0 },
        { mainId: 'Pop & New Wave',                     weight: 0.7 },
        { mainId: 'Rock',                               weight: 0.5 },
        { mainId: 'Deutsche Musik',                     weight: 0.5 },
        { mainId: 'Hip Hop / Rap',                      weight: 0.5 },
      ]},
    { id: 'Deutsche Musik', role: 'peak',
      neighbours: [
        { mainId: 'Pop & New Wave',                     weight: 1.0 },
        { mainId: 'EDM / Electronic',                   weight: 0.7 },
        { mainId: 'Synthwave / Electronica',            weight: 0.5 },
      ]},
  ],

  bridgeSubgenres: {
    'dance pop':           ['EDM / Electronic', 'Pop & New Wave', 'Deutsche Musik'],
    'synthpop':            ['Synthwave / Electronica', 'Rock', 'Pop & New Wave'],
    'ska punk':            ['Punk', 'Ska & Reggae'],
    'skate punk':          ['Punk', 'Ska & Reggae'],
    'rap metal':           ['Metal & Hard Rock', 'Hip Hop / Rap'],
    'nu metal':            ['Metal & Hard Rock', 'Hip Hop / Rap'],
    'eurodance':           ['EDM / Electronic', 'Pop & New Wave', 'Deutsche Musik'],
    'europop':             ['EDM / Electronic', 'Pop & New Wave', 'Deutsche Musik'],
    'new wave':            ['Rock', 'Punk', 'Pop & New Wave', 'Deutsche Musik'],
    'neue deutsche welle': ['Deutsche Musik', 'Rock', 'Pop & New Wave'],
    'schlager':            ['Deutsche Musik', 'Pop & New Wave'],
    'deutscher pop':       ['Deutsche Musik', 'Pop & New Wave'],
    'disco house':         ['EDM / Electronic', 'Funk, Soul & R&B', 'Synthwave / Electronica'],
    'italo disco':         ['EDM / Electronic', 'Funk, Soul & R&B', 'Synthwave / Electronica'],
    'hip house':           ['EDM / Electronic', 'Hip Hop / Rap'],
    'glam metal':          ['Metal & Hard Rock', 'Rock'],
    'hard rock':           ['Metal & Hard Rock', 'Rock'],
    'bluesrock':           ['Funk, Soul & R&B', 'Rock'],
    'klassischer rock':    ['Funk, Soul & R&B', 'Rock'],
    'southern rock':       ['Funk, Soul & R&B', 'Rock'],
  },

  pickerStrategy: {
    subgenreFirst: true,
    neighbourEarly: true,
    escalation: ['subgenre', 'mainGenre', 'bridgePivot', 'neighbourMain'],
  },
};

export function getNeighboursWeighted(mainId) {
  const m = GENRE_CONFIG.mainGenres.find(g => g.id === mainId);
  return m ? [...m.neighbours].sort((a,b) => b.weight - a.weight) : [];
}

export function getNeighbours(mainId) {
  return getNeighboursWeighted(mainId).map(n => n.mainId);
}

export function bridgeTags(mainId, neighbourId) {
  return Object.entries(GENRE_CONFIG.bridgeSubgenres)
    .filter(([, mains]) => mains.includes(mainId) && mains.includes(neighbourId))
    .map(([tag]) => tag);
}

export function bridgeTagsForMain(mainId) {
  return Object.entries(GENRE_CONFIG.bridgeSubgenres)
    .filter(([, mains]) => mains.includes(mainId))
    .map(([tag]) => tag);
}

export function getSubgenres(t) {
  return Array.isArray(t.genres_raw) ? t.genres_raw : [];
}

export function getGenreRole(mainId) {
  const m = GENRE_CONFIG.mainGenres.find(g => g.id === mainId);
  return m ? m.role : 'peak';
}

export function getRoleBonus(mainId, phase) {
  const m = GENRE_CONFIG.mainGenres.find(g => g.id === mainId);
  if (!m) return 0;
  if (phase === 'A' && m.role === 'warmup')   return  0.3;
  if (phase === 'D' && m.role === 'cooldown') return  0.3;
  if ((phase === 'A' || phase === 'D') && m.role === 'peak') return -0.2;
  return 0;
}
